### ISSUE TITLE
Make failure

### ISSUE THREAD

**Issue by hemstrow** [tplinderoth/ngsParalog#3]
Hey there!

I'm having some issues installing ngsParalog on a new ubuntu (20.04 LTS) install. Running `make` generates the following error:

g++ -c -O3 -Wall Stats.cpp
Stats.cpp: In constructor ‘NoDataException::NoDataException(const char*, unsigned int)’:
Stats.cpp:266:81: error: call of overloaded ‘runtime_error(ExceptionFormatter&)’ is ambiguous
  266 |  : std::runtime_error(ExceptionFormatter() << id << " " << pos << " has no data") {}
      |                                                                                 ^
In file included from parsePileup.h:9,
                 from Stats.cpp:11:
/usr/include/c++/9/stdexcept:230:5: note: candidate: ‘std::runtime_error::runtime_error(const char*)’
  230 |     runtime_error(const char*) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
/usr/include/c++/9/stdexcept:226:5: note: candidate: ‘std::runtime_error::runtime_error(const string&)’
  226 |     runtime_error(const string& __arg) _GLIBCXX_TXN_SAFE;
      |     ^~~~~~~~~~~~~
make: *** [Makefile:13: Stats.o] Error 1

This wasn't an issue during my previous install from ~2020 or so.

**Comment by OliverPStuart** [comment]
I have this same issue on Rocky Linux 8.6

**Comment by tplinderoth** [comment]
Thanks for the heads up, I needed to update the code for more recent compiler versions. I think I've fixed this now. Let me know if you still have issues compiling.

**Comment by OliverPStuart** [comment]
Thanks, this fixed the compilation issue and a quick test seems to be working fine

**Comment by tplinderoth** [comment]
Excellent. Let me know if you run into any issues.
